In [1]:
import numpy as np

a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b = np.array([10, 10, 10])
for a_, b_ in zip (a, b):
    print(a_)
    print(b_)

[0 1 2]
10
[3 4 5]
10
[6 7 8]
10


In [2]:
class Perceptron(object):
    def __init__(self, rate, iterations):
        self._rate = rate
        self._itrations = iterations
    
    def fit(self, X, y):
        self.w_ = np.zeros(1 + X.shape[1]) # w_ contains 1 weight per feature
        self.errors_ = []
        
        for _ in range(self.n_iter):
            errors = 0
            for xi, target in zip(X, y):
                update = self._rate * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
            return self


    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)
        
                
        