## NumPy tutorial
http://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial


In [1]:
import numpy as np

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.ndim

2

In [3]:
a.shape

(3, 5)

In [4]:
a.size

15

In [5]:
a.dtype

dtype('int64')

In [6]:
a.itemsize

8

In [7]:
a.data

In [8]:
type(a)

numpy.ndarray

In [9]:
np.array((1, 2, 3))

array([1, 2, 3])

In [10]:
np.array([1, 2, 3])

array([1, 2, 3])

In [11]:
b = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]], dtype=complex)

In [12]:
b.shape

(2, 3, 3)

In [13]:
b.size

18

In [14]:
b.dtype

dtype('complex128')

In [15]:
b.ndim

3

In [16]:
b


array([[[  1.+0.j,   2.+0.j,   3.+0.j],
        [  4.+0.j,   5.+0.j,   6.+0.j],
        [  7.+0.j,   8.+0.j,   9.+0.j]],

       [[ 10.+0.j,  11.+0.j,  12.+0.j],
        [ 13.+0.j,  14.+0.j,  15.+0.j],
        [ 16.+0.j,  17.+0.j,  18.+0.j]]])

In [17]:
c = np.zeros((4, 5, 2))

In [18]:
c

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [19]:
c.shape

(4, 5, 2)

In [20]:
c.ndim

3

In [21]:
d = np.empty((2, 3, 10), dtype=int)
d

array([[[     140209627229672,      140209627229672,      140209637536528,
                            1,  8444651245537485936,      140208926213768,
              140209641664512,  3563983470083427865,      140208926212808,
              140209641664544],
        [ 2481036311879757684,                    0,                    0,
          5863930400840532763,                    0,                    0,
          2314885532131011677,                    0,                    0,
          2710957243369009118],
        [                   0,                    0,  1130539976478199350,
              140208926215304,      140209641664576, -6860959944324332593,
              140209486057736,      140209641664608,                  240,
                           80]],

       [[                   0,      140209641664608,      140209641664832,
              140209562788672,      140209641394160,      140208926196720,
                            0, -5816492538014894679,      140209486070088,
  

In [22]:
np.arange(10, 100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
np.linspace(0, 2, 11)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [24]:
x = np.linspace(0, 2*np.pi, 100)
f = np.sin(x)

In [25]:
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ..., 
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [27]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a - b

array([20, 29, 38, 47])

In [28]:
a  <35

array([ True,  True, False, False], dtype=bool)

In [29]:
a * b

array([  0,  30,  80, 150])

In [30]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.arange(4).reshape(4, 1)
b

array([[0],
       [1],
       [2],
       [3]])

In [31]:
d = np.dot(a, b)

In [32]:
d

array([[20],
       [44]])

In [33]:
d.shape

(2, 1)

In [34]:
d.ndim

2

In [35]:
a = np.ones((2, 3))
b = np.random.random((2,3))
a *= 3
a

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [36]:
b


array([[ 0.48276588,  0.30711643,  0.70426381],
       [ 0.14252807,  0.46315642,  0.21985243]])

In [37]:
a += b
a

array([[ 3.48276588,  3.30711643,  3.70426381],
       [ 3.14252807,  3.46315642,  3.21985243]])

In [38]:
a.sum()

20.31968303594563

In [39]:
a.min()

3.1425280706279688

In [40]:
a.max()

3.704263807103326

In [41]:
a = np.linspace(1, 10, 3)
a

array([  1. ,   5.5,  10. ])

In [42]:
np.exp(a)

array([  2.71828183e+00,   2.44691932e+02,   2.20264658e+04])

In [43]:
np.sqrt(a)

array([ 1.        ,  2.34520788,  3.16227766])

In [44]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a[:6:2] = 100

In [46]:
a

array([100,   1, 100,   3, 100,   5,   6,   7,   8,   9])

In [47]:
a[::-1]

array([  9,   8,   7,   6,   5, 100,   3, 100,   1, 100])

In [48]:
for i in a:
    print(i ** (1/3.))

4.64158883361
1.0
4.64158883361
1.44224957031
4.64158883361
1.70997594668
1.81712059283
1.91293118277
2.0
2.08008382305


In [50]:
a = np.arange(100).reshape((2, 2, 25))
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
         91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [51]:
a[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
a[0, 0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
a[:, :, 1:3]

array([[[ 1,  2],
        [26, 27]],

       [[51, 52],
        [76, 77]]])

In [61]:
a = np.array([[5, 9], [2, 3]])
              
for e in a.flat:
    print(e)

5
9
2
3


In [62]:
a.ravel()

array([5, 9, 2, 3])

In [67]:
a = np.arange(12).reshape((2, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:
a.transpose()

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])